baseURL: https://hub.optuna.org/
languageCode: en-us
title: OptunaHub
theme: index
pygmentsUseClasses: true
enableInlineShortcodes: true
enableGitInfo: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
  goldmark:
    renderer:
      unsafe: true

params:
  showDescriptioninHome: true
  hideAllTagsinHome: true

permalinks:
  optuna_versions: "optuna_versions/:slug"
  tags: "tags/:slug"

taxonomies:
  optuna_version: "optuna_versions"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON # for search
